### PR TITLE
Rework/add home page sections and some texts, move media to dedicated page

### PR DESCRIPTION
**Pull request by fl0ge**
Update node to 16, webpack to 5  and other npm dependencies
Change menu
Gather webd related sections (about, features, papers, roadmap)
Gather network related sections (coin distribution, p2p network, pool stats) under Network menu link
Add getting started section with easy step to get into webd
Change Team to Community
Change Developers to Contributors
Move Media to a new pages
Remove newsletter form and move follow us links to footer

### CODE REVIEW

**Comment by ibudisteanu** [comment]
Changes to the bundles are not acceptable as it will be to complex to review. Everything else, except the bundles will be accepted.

**Comment by fl0ge** [comment]
Thanks @ibudisteanu for you review.
I removed the commit with node and packages updates.
Is it OK for you now?

**Comment by ibudisteanu** [comment]
I will accept the pull request, but I will overwrite the bundles in a few minutes. Thanks

**Comment by fl0ge** [comment]
Ah ok @ibudisteanu I think I misunderstood you about the bundles.
I've updated the files in public/WebDollar-dist/ because they were not up to date with the live website.
Do you mean that the node 16 and webpack 5 updates along other npm dependencies updates was OK? I was wondering if upgrading node was possible on your side and hosting side.

If it's possible on your side, I can submit a new PR with these node 16/npm packages updates only: please let me know.

**Comment by ibudisteanu** [comment]
I checked and this is what you did. You just updated the bundles from webdollar.io. It is fine. We can't merge without checking any changes to the javascript bundles as they are transpiled and it is hard to check the transpiled code.

I also checked the overall code and for me it works. I deleted node_modules and did a fresh install and it works. Thanks

**Comment by fl0ge** [comment]
Yes I understand about the bundles. And actually, it was only to have a local UI similar to the live one.
By the way, if you think it is useful to have most of latest npm updates, and as I think node 16 update along with other npm updates are useful to speed up building and testing locally, I've submitted #83

**Pull request merged**
