### PR TITLE
Adding Exchanges on the website

### PR DESCRIPTION
**Pull request by romeodutu**
SEO improvement
Build Exchange page and content.

### CODE REVIEW

**Review by morion4000 — COMMENTED** [review]
Is the wording on the Exchange hero done this way in order to increase SEO? It reads a little backwards to me.

**Comment by IonutAlexandruPanait** [comment]
I would take the text from the marketing team. Please get in touch with Cristian/Catherine.

I would make a dropdown in header and there to add a redirecte link to a special blogtype page for all exchange.

**Comment by romeodutu** [comment]
Yes, the text needs to be improved. It's perfect to talk to the marketing area. Thanks for your suggestions.

**Comment by romeodutu** [comment]
> Is the wording on the Exchange hero done this way in order to increase SEO? It reads a little backwards to me.
Yes, to use the Alt + Title correctly.  And use the correct code in general.

**Pull request closed without merging**
